// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Destination struct {
	ID     int32
	Name   pgtype.Text
	Region pgtype.Text
	Lon    pgtype.Float8
	Lat    pgtype.Float8
}
