// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDestination = `-- name: GetDestination :one
select id, name, region, lon, lat from destination
where id = $1 limit 1
`

func (q *Queries) GetDestination(ctx context.Context, id int32) (Destination, error) {
	row := q.db.QueryRow(ctx, getDestination, id)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.Lon,
		&i.Lat,
	)
	return i, err
}

const getDestinations = `-- name: GetDestinations :many
select id, name, region, lon, lat from destination
order by id desc
`

func (q *Queries) GetDestinations(ctx context.Context) ([]Destination, error) {
	rows, err := q.db.Query(ctx, getDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Destination
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.Lon,
			&i.Lat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDestination = `-- name: UpsertDestination :one
insert into destination (name, region, lon, lat)
values ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE
SET lon = EXCLUDED.lon,
    lat = EXCLUDED.lat
RETURNING id
`

type UpsertDestinationParams struct {
	Name   pgtype.Text
	Region pgtype.Text
	Lon    pgtype.Float8
	Lat    pgtype.Float8
}

func (q *Queries) UpsertDestination(ctx context.Context, arg UpsertDestinationParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertDestination,
		arg.Name,
		arg.Region,
		arg.Lon,
		arg.Lat,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
